quotes_app/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('authors/', views.authors, name='authors'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    
]

quotes_app/quotes_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),

]

quotes_app/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_app/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=120)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=120)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
         return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self) -> str:
         return f"{self.name}"


class Quote(models.Model):
    quote =  models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.text}"

quotes_app/quotes/forms.py
from django import forms
from .models import Quote, Author

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    tags = forms.CharField(max_length=255, label='Tags', required=True, help_text='Enter tags separated by commas')
    author = forms.CharField(max_length=255, label='Author', required=True)

    class Meta:
        model = Quote
        fields = ['quote']

quotes_app/quotes/views.py
import os
import json
from django.shortcuts import render, redirect
from .forms import AuthorForm, QuoteForm
from django.contrib.auth.decorators import login_required
from .models import Quote, Tag, Author

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def read_data_from_json(file_name):
    file_path = os.path.join(BASE_DIR, file_name)
    with open(file_path, 'r', encoding='utf-8') as json_file:
        data = json.load(json_file)
    return data

def main(request):
    quotes_data = read_data_from_json('quotes.json')
    return render(request, 'quotes/index.html', {'quotes': quotes_data})

def authors(request):
    authors_data = read_data_from_json('authors.json')
    return render(request, 'quotes/authors.html', {'authors': authors_data})

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            # Зберігаємо дані форми в новий словник
            new_author_data = {
                "fullname": form.cleaned_data["fullname"],
                "born_date": form.cleaned_data["born_date"],
                "born_location": form.cleaned_data["born_location"],
                "description": form.cleaned_data["description"]
            }

            # Зчитуємо дані з існуючого файлу authors.json
            authors_data = read_data_from_json('authors.json')

            # Додаємо нового автора до списку авторів
            authors_data.append(new_author_data)

            # Зберігаємо оновлені дані у файл authors.json
            with open(os.path.join(BASE_DIR, 'authors.json'), 'w', encoding='utf-8') as json_file:
                json.dump(authors_data, json_file, ensure_ascii=False, indent=4)

            return redirect(to='quotes:main')
    else:
        form = AuthorForm()

    return render(request, 'quotes/add_author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            tags = form.cleaned_data["tags"].split(',')
            author_name = form.cleaned_data["author"]
            quote_text = form.cleaned_data["quote"]

            
            author, created = Author.objects.get_or_create(fullname=author_name)

            
            quote = Quote.objects.create(quote=quote_text, author=author)
            for tag_name in tags:
                tag, created = Tag.objects.get_or_create(name=tag_name.strip())
                quote.tags.add(tag)

            # Отримайте поточні дані з quotes.json
            quotes_data = read_data_from_json('quotes.json')

            # Додайте нову цитату до списку цитат
            new_quote_data = {
                "_id": str(quote.id),  # ID цитати в базі даних Django
                "tags": tags,
                "author": author_name,
                "quote": quote_text
            }
            quotes_data.append(new_quote_data)

            # Збережіть оновлені дані у quotes.json
            with open(os.path.join(BASE_DIR, 'quotes.json'), 'w', encoding='utf-8') as json_file:
                json.dump(quotes_data, json_file, ensure_ascii=False, indent=4)

            return redirect('quotes:main')
    else:
        form = QuoteForm()

    return render(request, 'quotes/add_quote.html', {'form': form})

quotes_app/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
    <h1>Add Author</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Author</button>
    </form>
    <a href="{% url 'quotes:main' %}">Повернутись на головну сторінку</a>
{% endblock %}

quotes_app/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
    <h1>Add Quote</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.quote.id_for_label }}">Quote:</label>
            {{ form.quote }}
        </div>
        <div class="form-group">
            <label for="{{ form.tags.id_for_label }}">Tags (comma separated):</label>
            {{ form.tags }}
        </div>
        <div class="form-group">
            <label for="{{ form.author.id_for_label }}">Author:</label>
            {{ form.author }}
        </div>
        <button type="submit">Add Quote</button>
    </form>
    <a href="{% url 'quotes:main' %}">Повернутись на головну сторінку</a>
{% endblock %}

quotes_app/quotes/templates/quotes/authors.html
{% extends "quotes/base.html" %}

{% block content %}
    <h1>Authors</h1>
    <ul>
        {% for author in authors %}
            <li>
                <strong>{{ author.fullname }}</strong><br>
                Born: {{ author.born_date }} in {{ author.born_location }}<br>
                Description: {{ author.description }}
            </li>
        {% empty %}
            <li>No authors available</li>
        {% endfor %}
    </ul>

    <a href="/">Повернутись на головну сторінку</a><br>
    <a href="/add_author/">Add Author</a><br>
    <a href="/add_quote/">Add Quote</a><br>
    <a href="/login/">Login</a><br>
    
{% endblock %}

quotes_app/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            <ul>
                <li><a href="/" role="button"> Go back to the main page </a></li>
            </ul>
        </nav>
        {% block content %} {% endblock %}
    </main>

 
</body>

</html>

quotes_app/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% for quote in quotes %}
                <div class="quote-block">
                    <span class="text">{{ quote.quote }}</span>
                    <span>by <small class="author">{{ quote.author }}</small></span>
                    <div class="tags">
                        Tags:
                        {% for tag in quote.tags %}
                            <a class="tag" href="/tag/{{ tag|slugify }}/page/1/">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="buttons">
                {% if user.is_authenticated %}
                    <a href="{% url 'quotes:authors' %}" class="btn btn-primary">Authors</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-danger">Logout</a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">Signup</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}